import ExcelJS from "exceljs";import fs from "node:fs";import path from "node:path";import{randomUUID}from"node:crypto";import type{FinanceData,Transaction}from"./types";
export const file=path.resolve("server/data/finance-data.xlsx");
const defs={Transactions:["ID","Date","Type","Category","Description","Account","Payment Method","Amount","Notes"],Budgets:["ID","Month","Category","Amount"],Goals:["ID","Name","Target","Current","Due Date","Notes"],Loans:["ID","Name","Original","Balance","Rate","Minimum","Due Day"],Accounts:["ID","Name","Type","Opening","Balance","Institution"],Recurring:["ID","Name","Type","Category","Amount","Frequency","Next Date","Account"]} as const;
async function book(){const wb=new ExcelJS.Workbook();if(fs.existsSync(file))await wb.xlsx.readFile(file);for(const[name,headers]of Object.entries(defs)){if(!wb.getWorksheet(name)){const ws=wb.addWorksheet(name);ws.addRow(headers);ws.views=[{state:"frozen",ySplit:1}];ws.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};ws.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF0F172A"}}}}return wb}
const val=(v:any)=>v??"";const date=(v:any)=>v instanceof Date?v.toISOString().slice(0,10):String(v??"").slice(0,10);
export async function readAll():Promise<FinanceData>{const wb=await book(),rows=(s:string)=>{const a:any[][]=[];wb.getWorksheet(s)!.eachRow((r,i)=>{if(i>1&&r.getCell(1).value)a.push(r.values as any[])});return a};
return{transactions:rows("Transactions").map(v=>({id:String(v[1]),date:date(v[2]),type:String(v[3]) as any,category:String(val(v[4])),description:String(val(v[5])),account:String(val(v[6])),paymentMethod:String(val(v[7])),amount:Number(v[8]||0),notes:String(val(v[9]))})),budgets:rows("Budgets").map(v=>({id:String(v[1]),month:String(v[2]),category:String(v[3]),amount:Number(v[4]||0)})),goals:rows("Goals").map(v=>({id:String(v[1]),name:String(v[2]),target:Number(v[3]||0),current:Number(v[4]||0),dueDate:date(v[5]),notes:String(val(v[6]))})),loans:rows("Loans").map(v=>({id:String(v[1]),name:String(v[2]),original:Number(v[3]||0),balance:Number(v[4]||0),rate:Number(v[5]||0),minimum:Number(v[6]||0),dueDay:Number(v[7]||0)})),accounts:rows("Accounts").map(v=>({id:String(v[1]),name:String(v[2]),type:String(v[3]),opening:Number(v[4]||0),balance:Number(v[5]||0),institution:String(val(v[6]))})),recurring:rows("Recurring").map(v=>({id:String(v[1]),name:String(v[2]),type:String(v[3]) as any,category:String(v[4]),amount:Number(v[5]||0),frequency:String(v[6]),nextDate:date(v[7]),account:String(v[8])}))}}
const map:any={transactions:["Transactions",(x:any)=>[x.id,new Date(x.date+"T00:00:00"),x.type,x.category,x.description,x.account,x.paymentMethod,x.amount,x.notes]],budgets:["Budgets",(x:any)=>[x.id,x.month,x.category,x.amount]],goals:["Goals",(x:any)=>[x.id,x.name,x.target,x.current,new Date(x.dueDate+"T00:00:00"),x.notes]],loans:["Loans",(x:any)=>[x.id,x.name,x.original,x.balance,x.rate,x.minimum,x.dueDay]],accounts:["Accounts",(x:any)=>[x.id,x.name,x.type,x.opening,x.balance,x.institution]],recurring:["Recurring",(x:any)=>[x.id,x.name,x.type,x.category,x.amount,x.frequency,new Date(x.nextDate+"T00:00:00"),x.account]]};
export async function add(kind:keyof FinanceData,input:any){const wb=await book(),[sheet,toRow]=map[kind],item={...input,id:randomUUID()};wb.getWorksheet(sheet)!.addRow(toRow(item));await wb.xlsx.writeFile(file);return item}
export async function remove(kind:keyof FinanceData,id:string){const wb=await book(),[sheet]=map[kind],ws=wb.getWorksheet(sheet)!;let row=0;ws.eachRow((r,i)=>{if(i>1&&String(r.getCell(1).value)===id)row=i});if(row)ws.spliceRows(row,1);await wb.xlsx.writeFile(file);return!!row}
export async function updateTransaction(id:string,input:Partial<Transaction>){const data=await readAll(),old=data.transactions.find(x=>x.id===id);if(!old)return null;await remove("transactions",id);const wb=await book(),item={...old,...input,id};wb.getWorksheet("Transactions")!.addRow(map.transactions[1](item));await wb.xlsx.writeFile(file);return item}
export async function ensureWorkbook(){const wb=await book();await wb.xlsx.writeFile(file)}