import {useEffect,useMemo,useState} from "react"; import {ArrowDownCircle,ArrowUpCircle,Banknote,ChartNoAxesCombined,Download,Landmark,PiggyBank,Plus,Trash2,WalletCards} from "lucide-react"; import {PieChart,Pie,Cell,ResponsiveContainer,Tooltip} from "recharts";
type Tx={id:string;date:string;type:string;category:string;description:string;account:string;paymentMethod:string;amount:number;notes:string};
const cats=["Salary","Side Income","Housing","Utilities","Groceries","Dining","Transportation","Fuel","Insurance","Health","Education","Entertainment","Shopping","Subscriptions","Emergency Fund","General Savings","Stocks","Crypto","Personal Loan","Car Loan","Mortgage","Credit Card","Miscellaneous"];
const accounts=["Main Bank","Savings Account","Cash","Credit Card","Investment Account","Loan Account","Other"];
const methods=["Bank Transfer","Debit Card","Credit Card","Cash","Standing Order","Other"];
const types=["Income","Expense","Savings","Loan Payment","Investment","Transfer","Other"];
const money=(n:number)=>new Intl.NumberFormat("en-JM",{style:"currency",currency:"JMD",maximumFractionDigits:0}).format(n);
export default function App(){const [tx,setTx]=useState<Tx[]>([]),[showForm,setShowForm]=useState(false),[month,setMonth]=useState(new Date().toISOString().slice(0,7));
const load=()=>fetch("/api/transactions").then(r=>r.json()).then(setTx); useEffect(load,[]);
const filtered=useMemo(()=>tx.filter(x=>x.date.startsWith(month)),[tx,month]); const sum=(t:string)=>filtered.filter(x=>x.type===t).reduce((a,b)=>a+b.amount,0);
const income=sum("Income"),expenses=sum("Expense"),savings=sum("Savings"),investments=sum("Investment"),loans=sum("Loan Payment"),net=income-expenses-savings-investments-loans;
const pie=[{name:"Expenses",value:expenses},{name:"Savings",value:savings},{name:"Loans",value:loans},{name:"Investments",value:investments}].filter(x=>x.value>0);
async function del(id:string){await fetch("/api/transactions/"+id,{method:"DELETE"});load();}
return <div className="app-shell"><aside><div className="brand"><div className="brand-mark">PF</div><div><b>FinanceFlow</b><span>Excel-powered</span></div></div><nav><a className="active"><ChartNoAxesCombined/>Dashboard</a><a><WalletCards/>Transactions</a><a><PiggyBank/>Savings</a><a><Landmark/>Loans</a></nav><div className="aside-foot">Your data stays portable in Excel.</div></aside><main><header><div><p className="eyebrow">PERSONAL FINANCE</p><h1>Money overview</h1><p>Track cash flow without living inside a spreadsheet.</p></div><div className="header-actions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><a className="btn ghost" href="/api/export"><Download size={18}/>Excel</a><button className="btn primary" onClick={()=>setShowForm(true)}><Plus size={18}/>Add transaction</button></div></header>
<section className="cards">{[
["Income",income,<ArrowUpCircle/>,"positive"],["Expenses",expenses,<ArrowDownCircle/>,"negative"],["Savings",savings,<PiggyBank/>,"accent"],["Net cash flow",net,<Banknote/>,net<0?"negative":"positive"]].map(([l,v,i,c]:any)=><article className="metric" key={l}><div className={"metric-icon "+c}>{i}</div><span>{l}</span><strong className={v<0?"danger":""}>{money(v)}</strong></article>)}</section>
<section className="grid"><article className="panel"><div className="panel-head"><div><span>Allocation</span><h2>Where your money went</h2></div></div><div className="chart-wrap">{pie.length?<ResponsiveContainer width="100%" height={260}><PieChart><Pie data={pie} dataKey="value" innerRadius={68} outerRadius={98} paddingAngle={4}>{pie.map((_,i)=><Cell key={i} fill={["#ef4444","#14b8a6","#f59e0b","#8b5cf6"][i%4]}/>)}</Pie><Tooltip formatter={(v:any)=>money(Number(v))}/></PieChart></ResponsiveContainer>:<div className="empty">Add transactions to populate the chart.</div>}</div><div className="legend">{pie.map((x,i)=><span key={x.name}><i style={{background:["#ef4444","#14b8a6","#f59e0b","#8b5cf6"][i%4]}}/>{x.name} {money(x.value)}</span>)}</div></article>
<article className="panel"><div className="panel-head"><div><span>Recent activity</span><h2>Latest transactions</h2></div></div><div className="tx-list">{filtered.slice().reverse().slice(0,7).map(x=><div className="tx-row" key={x.id}><div><b>{x.description||x.category}</b><span>{new Date(x.date+"T00:00:00").toLocaleDateString()} · {x.type}</span></div><div className="tx-amount"><b className={x.type==="Income"?"gain":"spend"}>{x.type==="Income"?"+":"-"}{money(x.amount)}</b><button aria-label="Delete" onClick={()=>del(x.id)}><Trash2 size={16}/></button></div></div>)}{!filtered.length&&<div className="empty">No transactions for this month yet.</div>}</div></article></section>
{showForm&&<TransactionModal close={()=>setShowForm(false)} saved={()=>{setShowForm(false);load();}}/>}</main></div>}
function TransactionModal({close,saved}:{close:()=>void;saved:()=>void}){const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),type:"Expense",category:"Groceries",description:"",account:"Main Bank",paymentMethod:"Debit Card",amount:"",notes:""}),[error,setError]=useState(""); const set=(k:string,v:string)=>setForm({...form,[k]:v});
async function submit(e:any){e.preventDefault();setError("");const r=await fetch("/api/transactions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); if(!r.ok){setError((await r.json()).message);return} saved();}
return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><span>NEW TRANSACTION</span><h2>Add money activity</h2></div><button type="button" onClick={close}>×</button></div><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={e=>set("date",e.target.value)} required/></label><label>Type<select value={form.type} onChange={e=>set("type",e.target.value)}>{types.map(x=><option>{x}</option>)}</select></label><label>Category<select value={form.category} onChange={e=>set("category",e.target.value)}>{cats.map(x=><option>{x}</option>)}</select></label><label>Amount<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>set("amount",e.target.value)} placeholder="0.00" required/></label><label className="full">Description<input value={form.description} onChange={e=>set("description",e.target.value)} placeholder="What was this for?"/></label><label>Account<select value={form.account} onChange={e=>set("account",e.target.value)}>{accounts.map(x=><option>{x}</option>)}</select></label><label>Payment method<select value={form.paymentMethod} onChange={e=>set("paymentMethod",e.target.value)}>{methods.map(x=><option>{x}</option>)}</select></label><label className="full">Notes<textarea value={form.notes} onChange={e=>set("notes",e.target.value)} placeholder="Optional notes"/></label></div>{error&&<p className="error">{error}</p>}<div className="modal-actions"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn primary">Save transaction</button></div></form></div>}